name: Pixelblaze Firestorm
description: >-
 Pixelblaze Firestorm is a centralized control console for Pixelblaze WiFi LED controllers.
version: "0.1.0"
slug: "firestorm"
url: https://github.com/simap/Firestorm

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
panel_icon: "mdi:led-strip"
ingress: true
host_network: true
